name: assistant

services:
  model_handler:
    build: model_handler
    container_name: model_handler
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
